## Projekt Neuronales Netzwerk

### Keras und Tensorflow installieren

- Keras ist in Tensorflow Integriert worden.
- Keras ist in Python entwickelt, Tensorflow in C++
- Keras komofrtabele Schnittstelle um auf Tensorflow zuzugreifen
- es reicht aus, Tensorflow zu installieren.
- Tensorflow läuft nur mit Python bis zur Version 3.12.

In [4]:
!pip3 install tensorflow


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [5]:
import keras

In [6]:
keras.__version__

'3.8.0'

### Unsere Daten

Datenbank: FASHIONMNIST

- 10 Kategorien: 
  - T-Shirt
  - Trousers
  - Dress
  - Coat
  - Sandale
  - Shirt
  - Pullover
  - Sneaker
  - Bag
- jedes Bild ist 28 x 28 Pixel groß
- Bilder in Graustufen

Beispiele:

![](/Users/martin/Workspace/Jupyter_Notebooks/Info_KS/6_Artificial_Intelligence/images/The-FashionMNIST-dataset-consists-of-10-classes-of-monochrome-clothing-items-and-is.png){width=400px}


### Aufbau eines neuronales Netzwerk zur Erkennung eines T-Shirts.

- Entscheidungsfrage: Ist auf dem Bild ein T-Shirt zu sehen oder nicht?
- Aufbau:
  - Eingans-Layer: 28 x 28 Pixel, dh. 28*28=784 Eingänge
  - Hidden Layer: 100 Neuronen
  - Output-Layer: 1 Neuron mit der Ausgabe, ob es sich um ein T-Shirt handelt (1) oder nicht (0)
  

#### 1. Bilder einlesen

In [16]:
import gzip
import numpy as np 

def open_images(filename):
    with gzip.open(filename, "rb") as file:
        data = file.read()
        return np.frombuffer(data, dtype=np.uint8, offset = 16)\
            .reshape(-1, 28, 28)\
            .astype(np.float32)
        
def open_labels(filename):
    with gzip.open(filename, "rb") as file:
        data = file.read()
        return np.frombuffer(data, dtype = np.uint8, offset = 8)\



Ein Numpy Array wird erzeugt mit den eingelesenen Werten

In [ ]:
#Daten einlesen
X_training = open_images("train-images-idx3-ubyte.gz")

BadGzipFile: Not a gzipped file (b'\x00\x00')

In [ ]:
X_training

In [ ]:
X_training.shape

### Exkurs Numpy Array


- Modulimport 
  ```python 
  import numpy as np
  ```
- Numpy-Array
  - effizienter als Python-Listen
  - zusätzliche Operationen
  - Matrixausgabe möglich

In [7]:
a=np.array([1,2,3,4])
print (a)
print(a*2)
print(a+3)
print(a+a)
print(a*a)
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix)
print(matrix[0,1])
print(matrix[:,1])


[1 2 3 4]
[2 4 6 8]
[4 5 6 7]
[2 4 6 8]
[ 1  4  9 16]
[[1 2 3]
 [4 5 6]]
2
[2 5]


In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.imshow(X_training[0])
#plt.imshow(X_training[1])
#plt.imshow(X_training[2], cmap="gray_r")
plt.show

NameError: name 'X_training' is not defined

In [ ]:
#Label einlesen 
y_training = open_labels()

In [ ]:
#Beispiel
y_training[0]

In [ ]:
# Numpy Array Ausgeben und ein True dort eintragen
y_training
y_training == 0

### 2. Modell erstellen

![](/Users/martin/Workspace/Jupyter_Notebooks/Info_KS/6_Artificial_Intelligence/images/NN.png){width=400px}


In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model1 = Sequential()
model1.add(Dense(100, activation="sigmoid",input_shape=(784,))) #Hidden Layer wird zugefügt mit allen Gewichten definiert und 100 Neuronen
model1.add(Dense(1,activation="sigmoid"))

model1.compile(optimizer"sgd", loss="binary_crossentropy")
#wichtig für Compilierung eines effizienten Codes



### 3. Modell trainieren




In [ ]:
x_training.reshape(60000, 784)
model1.fit(a), y_training,