## Projekt Neuronales Netzwerk

### 1. Keras und Tensorflow installieren

- Keras ist in Tensorflow Integriert worden.
- Keras ist in Python entwickelt, Tensorflow in C++
- Keras komofrtabele Schnittstelle um auf Tensorflow zuzugreifen
- es reicht aus, Tensorflow zu installieren.
- Tensorflow läuft nur mit Python bis zur Version 3.12.

In [1]:
!pip3 install tensorflow

In [2]:
import keras

In [3]:
keras.__version__

'3.8.0'

### 2. Die Daten

Datenbank: FASHIONMNIST

- 10 Kategorien: 
  - T-Shirt
  - Trousers
  - Dress
  - Coat
  - Sandale
  - Shirt
  - Pullover
  - Sneaker
  - Bag
- jedes Bild ist 28 x 28 Pixel groß
- Bilder in Graustufen

Beispiele:

### 3. Aufbau eines neuronales Netzwerk zur Erkennung eines T-Shirts.

- Entscheidungsfrage: Ist auf dem Bild ein T-Shirt zu sehen oder nicht?
- Aufbau:
  - Eingans-Layer: 28 x 28 Pixel, dh. 28*28=784 Eingänge
  - Hidden Layer: 100 Neuronen
  - Output-Layer: 1 Neuron mit der Ausgabe, ob es sich um ein T-Shirt handelt (1) oder nicht (0)
  

#### 3.1. Bilder einlesen

In [4]:
import gzip
import numpy as np 

def open_images(filename):
    with gzip.open(filename, "rb") as file:
        data = file.read()
        return np.frombuffer(data, dtype=np.uint8, offset=16)\
            .reshape(-1, 28, 28)\
            .astype(np.float32)


Ein Numpy Array wird erzeugt mit den eingelesenen Werten

In [5]:
#Daten einlesen
x_training = open_images("train-images-idx3-ubyte.gz")

In [6]:
x_training

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
x_training.shape

(60000, 28, 28)

#### 3.2 Exkurs - Numpy-Array


- Modulimport 
  ```python 
  import numpy as np
  ```
- Numpy-Array
  - effizienter als Python-Listen
  - zusätzliche Operationen
  - Matrixausgabe möglich

In [8]:
a=np.array([1,2,3,4])
print (a)
print(a*2)
print(a+3)
print(a+a)
print(a*a)
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix)
print(matrix[0,1])
print(matrix[:,1])


[1 2 3 4]
[2 4 6 8]
[4 5 6 7]
[2 4 6 8]
[ 1  4  9 16]
[[1 2 3]
 [4 5 6]]
2
[2 5]


#### Exkurs - Ende

In [9]:
#!pip3 install matplotlib

In [10]:
#%matplotlib inline
import matplotlib.pyplot as plt

plt.imshow(x_training[0])
#plt.imshow(x_training[1])
#plt.imshow(X_training[2], cmap="gray_r")
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

<Figure size 1650x1050 with 1 Axes>

### 3.3 Daten einlesen

In [11]:
def open_labels(filename):
    with gzip.open(filename, "rb") as file:
        data = file.read()
        return np.frombuffer(data, dtype=np.uint8, offset=8)


In [12]:
#Label einlesen 
y_training = open_labels("train-labels-idx1-ubyte.gz")

In [13]:
# Label anzeigen
y_training

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

#### 3.4. Modell erstellen

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
model1 = Sequential()
# Alle Gewichte verknüpft : Dense
# Aktivivierungsfunktion : Sigmoid
# Es werden 784 Pixel, also 784 Zahlen an 784 Eingänge übergeben
# 100 Neuronen

model1.add(Dense(100, activation="sigmoid",input_shape=(784,))) 
# Ausgabeschicht hat nur ein Neuron
model1 .add(Dense(1, activation="sigmoid"))

# Optimizer : Lernverfahren für die Gewichte
# loss : Standardwert

model1.compile(optimizer="sgd", loss="binary_crossentropy")
#wichtig für Compilierung eines effizienten Codes



/Users/martin/.pyenv/versions/3.12.6/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### 4. Modell trainieren




#### 4.1 Form der Label anpassen

In [16]:
y_training

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

Schreibe dort True rein, wo im Array 0 steht. Der Wert Null entspricht einem T-Shirt

In [17]:
y_training == 0

array([False,  True,  True, ..., False,  True, False])

Dieses Ergebnis ist nicht gespeichert. Man muss es noch der Variablen `y_training` zuordnen.

In [18]:
# Ergebnisse des Vergleichs sind temporär. daher müssen sie wieder in die Variable y_training geschrieben werden.abs 
y_training = y_training == 0

#### 4.2 Form der Daten anpassen

In [19]:
x_training.reshape(60000, 784)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

Daten müssen angepasst in der Form angepasst. Wir brauchen 60.000 Datenstränge, die jeweils 784 Daten enthalten. Dafür benutzen wir die Funktion `reshape`

### 4.3 Training

In [ ]:
# epochs : 10 mal werden die Daten durchlaufen
# batch : 1000 Bilder, dann werden die Gewichte adaptiert

model1.fit(
    x_training.reshape(60000, 784),
    y_training,
    epochs = 10,
    batch_size =1000)

### 5. Vorhersage

#### 5.1 Beispiel 1

In [21]:
print(y_training[0])

False


Das erste Bild ansehen mit `matplotlib` 

In [22]:
plt.imshow(x_training[0])

<Figure size 1650x1050 with 1 Axes>

Unser kNN bekommt das erste Bild unserer Trainingsdaten `x_training` übergeben und soll entscheiden, ob es sich dabei um ein T-Shirt handelt, oder nicht.

In [ ]:
model1.predict(x_training[0].reshape(1,784))

##### Ergebnis: Zu 0,003% stellt das Bild 1 ein T-Shirt dar

#### Beispiel 2:

In [24]:
print(y_training[1])

True


In [25]:
plt.imshow(x_training[1])

<Figure size 1650x1050 with 1 Axes>

Unser kNN bekommt das zweite  Bild unserer Trainingsdaten `x_training` übergeben und soll entscheiden, ob es sich dabei um ein T-Shirt handelt, oder nicht.

In [ ]:
model1.predict(x_training[1].reshape(1,784))

##### Ergebnis: Zu 82,28% stellt das Bild 2 ein T-Shirt dar.

### 6. Genauigkeit berechnen

Aus dem Prozentwert soll eine Aussage getroffen werden. Cut of ist 50%
Das Maß Geanuigkeit gibt an, wie gut das Neuronale Nezt ist.

In [ ]:
# y_training_predict = model1.predict(x_training.reshape(60000, 784))

In [28]:
y_training_predict

array([[0.00205277],
       [0.80220866],
       [0.09918989],
       ...,
       [0.03473911],
       [0.5544094 ],
       [0.01608302]], dtype=float32)

In [29]:
np.round(y_training_predict)

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]], dtype=float32)

Vergleich mit den echten Labels (y-Daten)

In [30]:
y_training

array([False,  True,  True, ..., False,  True, False])

Format muss angepasst werden

In [31]:
np.round(y_training_predict).reshape(60000)
#np.round(y_training_predict).reshape(-1) ist einen Zahlunabhängige Alternative 


array([0., 1., 0., ..., 0., 1., 0.], dtype=float32)

Die 60.000 Werte stehen jetzt immer hintereinander

Vergleich der Daten

In [32]:
np.round(y_training_predict).reshape(-1) == y_training

array([ True,  True, False, ...,  True,  True,  True])

In [33]:
np.mean(np.round(y_training_predict).reshape(-1) == y_training)

np.float64(0.9546166666666667)

Es wurde mit dem NN eine Genauigkeit von 95%. Die Genauigkeit wurde manuel bestimmt. Mit Keras geht das auch einfacher.

In [34]:
model1.compile(optimizer="sgd", loss="binary_crossentropy", metrics=["accuracy"])

In [35]:
model1.fit(
    x_training.reshape(60000, 784),
    y_training,
    epochs = 10,
    batch_size =1000)

Epoch 1/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 13s 231ms/step - accuracy: 0.9610 - loss: 0.0984


17/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9557 - loss: 0.1135   


33/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9555 - loss: 0.1152


48/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9555 - loss: 0.1157


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9553 - loss: 0.1162


Epoch 2/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9670 - loss: 0.1011


15/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9581 - loss: 0.1124 


30/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9569 - loss: 0.1141


46/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9562 - loss: 0.1150


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9559 - loss: 0.1155


Epoch 3/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9570 - loss: 0.1136


15/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9543 - loss: 0.1158 


29/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9547 - loss: 0.1152


43/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9548 - loss: 0.1152


56/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9548 - loss: 0.1152


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9548 - loss: 0.1153


Epoch 4/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.9450 - loss: 0.1415


16/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9499 - loss: 0.1234 


30/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9515 - loss: 0.1203


44/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9523 - loss: 0.1190


58/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9529 - loss: 0.1178


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9530 - loss: 0.1177


Epoch 5/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9450 - loss: 0.1214


15/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9514 - loss: 0.1185 


27/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9534 - loss: 0.1159


38/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9539 - loss: 0.1150


49/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9541 - loss: 0.1148


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9543 - loss: 0.1145


Epoch 6/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.9610 - loss: 0.1110


13/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9568 - loss: 0.1148 


27/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9556 - loss: 0.1138


41/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9551 - loss: 0.1136


55/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9550 - loss: 0.1134


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9550 - loss: 0.1133


Epoch 7/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9630 - loss: 0.1019


12/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9580 - loss: 0.1084 


23/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9575 - loss: 0.1095


32/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9573 - loss: 0.1099


40/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9572 - loss: 0.1099


53/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9570 - loss: 0.1099


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9570 - loss: 0.1100


Epoch 8/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.9560 - loss: 0.1074


16/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9560 - loss: 0.1099 


31/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9563 - loss: 0.1102


46/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9562 - loss: 0.1102


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9561 - loss: 0.1103


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9561 - loss: 0.1103


Epoch 9/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9490 - loss: 0.1200


14/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9538 - loss: 0.1181 


27/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9548 - loss: 0.1153


41/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9555 - loss: 0.1133


55/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9557 - loss: 0.1123


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9557 - loss: 0.1120


Epoch 10/10



 1/60 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9560 - loss: 0.1180


16/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9561 - loss: 0.1111 


31/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9560 - loss: 0.1110


45/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9560 - loss: 0.1108


59/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9561 - loss: 0.1103


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9562 - loss: 0.1103


In [36]:
model1.evaluate(x_training.reshape(60000, 784), y_training)


   1/1875 ━━━━━━━━━━━━━━━━━━━━ 2:53 93ms/step - accuracy: 0.9375 - loss: 0.2095


  72/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 706us/step - accuracy: 0.9566 - loss: 0.1148 


 151/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 670us/step - accuracy: 0.9578 - loss: 0.1091


 233/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 650us/step - accuracy: 0.9586 - loss: 0.1068


 315/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - accuracy: 0.9585 - loss: 0.1059


 397/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - accuracy: 0.9583 - loss: 0.1057


 480/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step - accuracy: 0.9581 - loss: 0.1057


 558/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - accuracy: 0.9579 - loss: 0.1057


 628/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.9577 - loss: 0.1059


 701/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.9576 - loss: 0.1059


 783/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.9575 - loss: 0.1060


 865/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step - accuracy: 0.9575 - loss: 0.1060


 947/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.9575 - loss: 0.1061


1029/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step - accuracy: 0.9574 - loss: 0.1061


1112/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - accuracy: 0.9574 - loss: 0.1062


1195/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - accuracy: 0.9574 - loss: 0.1062


1276/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - accuracy: 0.9573 - loss: 0.1063


1359/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - accuracy: 0.9573 - loss: 0.1064


1442/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.9573 - loss: 0.1064


1525/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.9572 - loss: 0.1065


1608/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step - accuracy: 0.9572 - loss: 0.1065


1691/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.9572 - loss: 0.1066


1773/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.9572 - loss: 0.1066


1856/1875 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.9571 - loss: 0.1067


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 630us/step - accuracy: 0.9571 - loss: 0.1067


[0.10724449157714844, 0.9567999839782715]

Der erste Wert der Liste sind die Kosten,
der zweit Wert der Liste ist die Genauigkeit.